name: NetLRTS Linux buildold

on: pull_request

jobs:
  build:
    timeout-minutes: 90

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build
      run: ./buildold all-test netlrts-linux-x86_64 -g -j4 --with-production
    - name: test
      run: make -C netlrts-linux-x86_64/tmp test TESTOPTS="++local"
    - name: testp P=2
      run: make -C netlrts-linux-x86_64/tmp testp TESTOPTS="++local" P=2
    - name: testp P=3
      run: make -C netlrts-linux-x86_64/tmp testp TESTOPTS="++local" P=3
