name: ChaNGa

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build-charm++
      run: ./build ChaNGa netlrts-linux-x86_64 -g -j4 --with-production
    - name: build-changa
      run: |
        git clone https://github.com/N-bodyshop/utility
        git clone https://github.com/N-bodyshop/changa
        cd changa
        ./configure
        make -j4
    - name: test-changa
      run: |
        cd changa/teststep
        make test
