name: Sphinx-doc

# Check if documentation builds with sphinx. Only triggered if a file
# in doc/ is changed.

on:
  pull_request:
    paths: 
      - 'doc/**'

jobs:
  sphinx-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    -
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install prerequisites
      run: pip3 install sphinx sphinx_rtd_theme        
    - name: Run sphinx
      run: |
        cd doc
        make html
