name: MPI Linux SMP

on: pull_request

jobs:
  build:
    timeout-minutes: 60

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install-prerequisites
      run: sudo apt-get update && sudo apt-get install -y mpich libmpich-dev
    - name: build
      run: ./build all-test mpi-linux-x86_64 smp --build-shared --with-production --enable-error-checking --enable-lbuserdata -j3 -g -Werror=vla
      # TODO: this should build tests with "-charm-shared". See #2735 on why this is not done currently.
    - name: test
      run: make -C mpi-linux-x86_64-smp/tmp test TESTOPTS="+setcpuaffinity"
    # Disabled due to several hangs and segfaults.
    #- name: testp
    #  run: make -C mpi-linux-x86_64-smp/tmp testp P=4 TESTOPTS="+setcpuaffinity ++ppn 2"
