name: NAMD

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install-prerequisites
      run: |
        sudo apt-get update
        sudo apt-get -y install sfftw-dev
        # test build without Fortran support
        sudo apt-get -y remove gfortran
    - name: build-charm++
      run: ./build LIBS netlrts-linux-x86_64 -g -j4 --with-production
    - name: build-namd
      run: |
        cd ..
        git clone https://${{ secrets.NAMD_CI_USERNAME_TOKEN }}@gitlab.com/tcbgUIUC/namd.git
        cd namd
        ./config Linux-x86_64-g++ --charm-base ../charm --charm-arch netlrts-linux-x86_64 --without-tcl
        cd Linux-x86_64-g++
        make -j4
    - name: test-namd-alanin
      run: |
        cd ../namd/Linux-x86_64-g++
        ./charmrun ++local +p2 ./namd2 src/alanin

    - name: Cache apoa1 files
      id: cache-apoa1-files
      uses: actions/cache@v2.0.0
      with:
        path: ~/namddata/apoa1
        key: namd-apoa1-files
    - name: Download apoa1 files
      if: steps.cache-apoa1-files.outputs.cache-hit != 'true'
      run: |
        mkdir -p ~/namddata
        cd ~/namddata
        wget http://www.ks.uiuc.edu/Research/namd/utilities/apoa1.tar.gz
        tar xzf apoa1.tar.gz
        sed -i 's,500,250,' apoa1/apoa1.namd # Reduce number of steps
        sed -i 's,/usr/tmp,/tmp,' apoa1/apoa1.namd # Change output prefix
        rm apoa1.tar.gz

    - name: test-namd-apoa1
      run: |
        cd ../namd/Linux-x86_64-g++
        ./charmrun ++local +p4 ./namd2 ~/namddata/apoa1/apoa1.namd
