name: NetLRTS Darwin

on: pull_request

jobs:
  build:
    timeout-minutes: 60

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: ./build all-test netlrts-darwin-x86_64 --build-shared --with-production --enable-error-checking --enable-lbuserdata -j3 -g -Werror=vla
      # TODO: this should build tests with "-charm-shared". See #2735 on why this is not done currently.
    - name: test
      run: make -C netlrts-darwin-x86_64/tmp test TESTOPTS="++local"
    - name: testp
      run: make -C netlrts-darwin-x86_64/tmp testp P=2 TESTOPTS="++local"
