name: NetLRTS Linux SyncFT

on: pull_request

jobs:
  build:
    timeout-minutes: 90

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build
      run: ./build all-test netlrts-linux-x86_64 syncft -j2 -g
    - name: test
      run: make -C netlrts-linux-x86_64-syncft/tmp syncfttest TESTOPTS="++local"
