name: MPI Linux SyncFT

on: pull_request

jobs:
  build:
    timeout-minutes: 90

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install-prerequisites
      run: sudo apt-get update && sudo apt-get install -y mpich libmpich-dev
    - name: build
      run: ./build all-test mpi-linux-x86_64 syncft -j2 -g
    - name: test
      run: make -C mpi-linux-x86_64-syncft/tmp mpisyncfttest
