name: Verbs Linux Buildonly Tarball

# Buildonly test, as the machine layer needs an actual device to run.
# Also test packaging a tarball and building from it.
# Since it is buildonly, test both build and buildold with the tarball.

on: pull_request

jobs:
  build:
    timeout-minutes: 45

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install-prerequisites
      run: |
        sudo apt-get update
        sudo apt-get -y install libibverbs-dev
    - name: package-tarball
      run: |
        ./package-tarball.sh
        cd ..
        tar -xzf charm/charm-*.tar.gz
    - name: build-smp
      run: |
        cd ../charm-*
        # TODO: this should build tests with "-charm-shared". See #2735 on why this is not done currently.
        ./build all-test verbs-linux-x86_64 smp -j4 -g --build-shared
    - name: buildold-nonsmp
      run: |
        cd ../charm-*
        # TODO: this should build tests with "-charm-shared". See #2735 on why this is not done currently.
        ./buildold all-test verbs-linux-x86_64 -j4 -g --build-shared
