version: 2.1
jobs:
  NetLRTS:
    machine:
      image: ubuntu-1604:201903-01

    steps:
      - checkout
      - run:
          name: Build
          command: ./build all-test netlrts-linux-x86_64 -j3 --with-production --enable-error-checking --enable-lbuserdata -g -Werror=vla
      - run:
          name: Test
          command: make -C netlrts-linux-x86_64/tmp test TESTOPTS="++local"
      - run:
          name: TestP P=2
          command: make -C netlrts-linux-x86_64/tmp testp P=2 TESTOPTS="++local"

  NetLRTS-smp:
    machine:
      image: ubuntu-1604:201903-01

    steps:
      - checkout
      - run:
          name: Build
          command: ./build all-test netlrts-linux-x86_64 smp -j3 --with-production --enable-error-checking --enable-lbuserdata -g -Werror=vla
      - run:
          name: Test
          command: make -C netlrts-linux-x86_64-smp/tmp test TESTOPTS="++local +setcpuaffinity +CmiSleepOnIdle"
      - run:
          name: TestP P=4 PPN=2
          command: make -C netlrts-linux-x86_64-smp/tmp testp P=4 TESTOPTS="++local +setcpuaffinity +CmiSleepOnIdle ++ppn 2"

workflows:
  version: 2
  build:
    jobs:
      - NetLRTS
      - NetLRTS-smp
